export const MODULE_LIST = [
  {
    id: 'introduction',
    title: 'Introduction',
    path: '/module/introduction',
    icon: 'BookOpen',
    description: 'Welcome to BlockSim. Start here to understand the basics.',
  },
  {
    id: 'hash',
    title: 'Hash',
    path: '/module/hash',
    icon: 'Hash',
    description: 'Learn how hashing secures data and ensures integrity.',
  },
  {
    id: 'block',
    title: 'Block',
    path: '/module/block',
    icon: 'Box',
    description: 'Understand the fundamental building block of the chain.',
  },
  {
    id: 'blockchain',
    title: 'Blockchain',
    path: '/module/blockchain',
    icon: 'Link',
    description: 'See how blocks link together to form an immutable chain.',
  },
  {
    id: 'distributed',
    title: 'Distributed',
    path: '/module/distributed',
    icon: 'Users',
    description: 'Explore how a peer-to-peer network maintains the ledger.',
  },
  {
    id: 'tokens',
    title: 'Tokens',
    path: '/module/tokens',
    icon: 'Coins',
    description: 'Learn about digital assets and value transfer.',
  },
  {
    id: 'coinbase',
    title: 'Coinbase',
    path: '/module/coinbase',
    icon: 'CircleDollarSign',
    description: 'Discover how new coins are created in the first transaction.',
  },
  {
    id: 'keys',
    title: 'Keys',
    path: '/module/keys',
    icon: 'Key',
    description: 'Understand Public and Private keys for identity and security.',
  },
  {
    id: 'signatures',
    title: 'Signatures',
    path: '/module/signatures',
    icon: 'PenTool',
    description: 'Learn how digital signatures prove ownership and authenticity.',
  },
  {
    id: 'transaction',
    title: 'Transaction',
    path: '/module/transaction',
    icon: 'ArrowRightLeft',
    description: 'Combine concepts to securely transfer value.',
  },
  {
    id: 'pow',
    title: 'Proof of Work',
    path: '/module/pow',
    icon: 'Cpu',
    description: 'The consensus mechanism that secures the network.',
  },
  {
    id: 'mining',
    title: 'Mining',
    path: '/module/mining',
    icon: 'Hammer',
    description: 'Experience the process of validating blocks and earning rewards.',
  },
  {
    id: 'difficulty',
    title: 'Difficulty',
    path: '/module/difficulty',
    icon: 'Gauge',
    description: 'See how the network adjusts difficulty to maintain block time.',
  },
  {
    id: 'smart-contracts',
    title: 'Smart Contracts',
    path: '/module/smart-contracts',
    icon: 'FileCode',
    description: 'Programmatic rules that execute automatically on the chain.',
  },
];

export const DIFFICULTY_LEVELS = [1, 2, 3, 4, 5, 6];
